CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS players (
    player_id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    login_id   VARCHAR(32) NOT NULL UNIQUE,
    wins       INTEGER NOT NULL DEFAULT 0 CHECK (wins >= 0),
    losses     INTEGER NOT NULL DEFAULT 0 CHECK (losses >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);